### ISSUE TITLE
State of android app question 

### ISSUE THREAD

**Issue by ziomek64** [safing/portmaster-android#22]
Is this still being worked on or abandoned?

**Comment by vlabo** [comment]
At the moment we are not working on it. We plan to resume development when we have more development capacity.
You can read more about it here:
https://safing.io/blog/2024/01/02/JourneyUpdate2401/#disabled?source=Portmaster

**Comment by ziomek64** [comment]
> At the moment we are not working on it. We plan to resume development when we have more development capacity.
> You can read more about it here:
> https://safing.io/blog/2024/01/02/JourneyUpdate2401/#disabled?source=Portmaster

Thanks for answering
